messages:
  no-perm: "&8[&5Announce&8] &7你没有足够的权限执行该命令."
  reload-config: "&8[&5Announce&8] &7重载配置文件."

schedule:
  '1':
    text:
    - |-
      Welcome to ProMC Network
      Have fun in ProMC Network!
    - |-
      Those message under schedule
      will be random.
      If u want to just specific one
      just to leave it one single message
    commands:
    - 'broadcast Success trigger schedule task'
    time: '12:00'
  '2':
    text: |-
      You're %player_name%.
      Nice to see you in ProMC Network.
    time: '16:00'

timer:
  '1':
    text:
    - |-
      Welcome to ProMC Network
      This message will trigger every 5 mins.
    - |-
      Hi %player_name%
      You now see the second message.
    - 'Of course, u could\njust try to use ''\n'' to switch line.'
    commands:
    - 'broadcast Success trigger timer task'
    time: 300